<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Asset Paths
    |--------------------------------------------------------------------------
    |
    | Here you can specify the paths to your custom fonts and background images.
    | By default, it uses the assets included with the package.
    |
    */
    'fonts_path' => __DIR__.'/../assets/fonts',
    'backgrounds_path' => __DIR__.'/../assets/backgrounds',

    /*
    |--------------------------------------------------------------------------
    | Allowed Captcha Characters
    |--------------------------------------------------------------------------
    |
    | A list of characters that will be used in the text-based captcha
    | generated by the TextGenerator.
    |
    */
    'characters' => [
        '0', '1', '2', '3', '4', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'm', 'n', 'p', 'q',
        'r', 't', 'u', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'M', 'N', 'P', 'Q', 'R', 'T', 'U',
        'X', 'Y', 'Z',
    ],

    /*
    |--------------------------------------------------------------------------
    | Captcha Profiles
    |--------------------------------------------------------------------------
    |
    | You can define multiple captcha profiles with different settings.
    |
    */
    'default' => [
        'driver' => 'text',
        'length' => 6,
        'sensitive' => true,
        'expire' => 60,
        'encrypt' => false,

        'image' => [
            'width' => 120,
            'height' => 40,
            'quality' => 90,
            'fontColors' => ['#2c3e50', '#c0392b', '#16a085', '#8e44ad', '#303f9f'],
            'bgColor' => '#ecf2f4',
            'bgImage' => true,
            'lines' => 6,
            'angle' => 10,
            'kerning' => -1,
            'sharpen' => 0,
            'blur' => 0,
            'contrast' => 0,
            'invert' => false,
        ],
    ],
    'math' => [
        'driver' => 'math',
        'operators' => ['+', '-'],
        'expire' => 60,
        'encrypt' => false,

        'image' => [
            'width' => 150,
            'height' => 40,
            'fontColors' => ['#333'],
            'bgColor' => '#f1f1f1',
            'lines' => 2,
            'angle' => 5,
            'kerning' => 0,
        ],
    ],
    'flat' => [
        'driver' => 'text',
        'length' => 6,
        'sensitive' => true,
        'expire' => 60,
        'encrypt' => false,

        'image' => [
            'width' => 160,
            'height' => 46,
            'bgImage' => false,
            'bgColor' => '#ecf2f4',
            'fontColors' => ['#2c3e50', '#c0392b', '#16a085', '#c0392b', '#8e44ad', '#303f9f', '#f57c00', '#795548'],
            'lines' => 6,
            'blur' => 2,
            'contrast' => -5,
        ],
    ],
    'inverse' => [
        'driver' => 'text',
        'length' => 5,
        'sensitive' => true,
        'expire' => 60,
        'encrypt' => false,

        'image' => [
            'width' => 120,
            'height' => 40,
            'bgColor' => '#333',
            'fontColors' => ['#f1f1f1'],
            'lines' => 0,
            'angle' => 0,
            'sharpen' => 10,
            'blur' => 2,
            'contrast' => -5,
            'invert' => true,
        ],
    ],
];
